communitiesuk/digital-form-builder-adapter

runner/src/server/plugins/engine/models/AdapterFormModel.ts, runner/src/server/plugins/engine/page-controllers/AdapterSummaryPageController.ts, runner/src/server/plugins/engine/page-controllers/DefaultPageController.ts
https://dluhcdigital.atlassian.net/browse/FS-4557 
Summary: 
As a user I need to save form filled content in a given api location.
Description:
When form has been created using the form designer there are few different ways to output the content of the forms data, with this JIRA we are planing to give new way to save the content and content will be saved each form that you filled in and those data will be persisted in a given api location.
Scope:
This should allow to get a link or a config text to determine the location in the runtime of the save, and if config used it should resolve the link from the configurations that we provide.
Once out put is added each form should call the end point with the data to save.
Validate the output configurations.
=> FS-4557: Feature - Form Runner & Designer - Save current form before go forward

runner/locales/cy.json, runner/locales/en.json, runner/src/server/plugins/engine/page-controllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/page-controllers/RepeatingSummaryPageController.ts, runner/src/server/views/summary.html
https://mhclgdigital.atlassian.net/browse/FS-3824
https://mhclgdigital.atlassian.net/browse/FS-2023
- Welsh translation added for Mark as complete label at the summary page and for "Remove" option in the build text field component
- Select Welsh language, Go to a summary page in any form, it should have correct Welsh Translation for Mark as complete
- Go to a form that has build text field component, it should have correct Welsh translation for "Remove" text
Mark as complete:
Remove:
=> FS-3824: MarkAsComplete and Remove Welsh added

fsd_config/form_jsons/cof/cy/gwybodaeth-am-y-sefydliad-cof.json, fsd_config/form_jsons/cof/cy/gwybodaeth-am-yr-ased-cof.json, runner/locales/cy.json, runner/locales/en.json, runner/src/server/index.ts, runner/src/server/plugins/engine/MainPlugin.ts, runner/src/server/plugins/engine/api/RegisterFormPublishApi.ts, runner/src/server/plugins/engine/components/AdapterTelephoneNumberField.ts, runner/src/server/plugins/engine/components/AdapterYesNoField.ts, runner/src/server/plugins/engine/components/UkAddressField.ts, runner/src/server/plugins/engine/components/index.ts, runner/src/server/plugins/engine/models/AdapterFormModel.ts, runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts, runner/src/server/plugins/engine/page-controllers/PlaybackUploadPageController.ts, runner/src/server/plugins/engine/page-controllers/SummaryPageController.ts, runner/src/server/plugins/engine/service/TranslationLoaderService.ts, runner/src/server/types.ts
Adding CY and EN translations for the following parts, also it contains error messages for each validations
1. Telephone number field
2. Uk address field
3. Yes or no field
4. Some of the common error messages
For non-translated CY will have `(cy)` tag in as a prefix for identification purpose before the fund rounds open planning to remove them or replace with actual translations
1. https://mhclgdigital.atlassian.net/browse/FS-4499
2. https://mhclgdigital.atlassian.net/browse/FS-4500
3. https://mhclgdigital.atlassian.net/browse/FS-4505
4. https://mhclgdigital.atlassian.net/browse/FS-4507
5. https://mhclgdigital.atlassian.net/browse/FS-4510
=> Translation changes for following jira tickets [FS-4499/FS-4500/FS-4505/FS-4507/FS-4510]

runner/config/custom-environment-variables.json, runner/config/default.js, runner/src/server/plugins/engine/models/ViewModelBase.ts
When there are default type of sections and user need to ignore showing the sections that was not answered will be able to use this feature and ignoreSectionsFromSummary is a array of section names that need to give to ignore in the summary page
=> ignore some sections from the summary page

designer/client/components/Page/AdapterPage.tsx, designer/client/components/multiinput-field-edit/MultiInputFieldEdit.tsx, e2e-test/cypress/e2e/designer/multiInputFieldEdit.feature, e2e-test/cypress/e2e/formPages.feature, e2e-test/cypress/e2e/listComponents.feature, e2e-test/cypress/support/step_definitions/runner/i_preview_the_page_string_without_href.js, runner/src/server/plugins/engine/page-controllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/views/components/multiinputfield.html
https://mhclgdigital.atlassian.net/browse/FS-4742
Updated multiinputfield.html to correctly represent UK address fields, ensuring accurate formatting. Enhance the designer to properly sync controller-level changes with the runner. Additionally, introduced a multiline input component within the multi-input field to support multiline text inputs as required.
=> FS-4742 multi input field addressfield fix in runner and allow multi line textfield and enhancements in designer on multi input field

designer/client/components/Page/AdapterPage.tsx
https://mhclgdigital.atlassian.net/browse/FS-4776
And to fix the above issue users need to add sections but once user added the section after creating the conditions it gives an white page (error) since section name is not updated in the conditions.
For more info : [Confluence](https://mhclgdigital.atlassian.net/wiki/spaces/FS/pages/336068651/Issue+Analysis+and+Improvement+Plan+for+XGovFormBuilder+Designer+Tool+Adapter+Version)
=> FS-4776: Condition fix when added a section after adding a condition

designer/client/components/Page/AdapterPage.tsx, e2e-test/cypress/e2e/designer/startPage.feature, e2e-test/cypress/e2e/formPages.feature, e2e-test/cypress/support/step_definitions/runner/I_am_creating_a_section .js, e2e-test/cypress/support/step_definitions/runner/i_see_the_heading_string.js
https://mhclgdigital.atlassian.net/browse/FS-4777
According to the runner code, conditions are checked based on sections. However, if the user decides to change their answers on the last page (the Summary page), these conditions are not immediately checked. This is because reaching the Summary page indicates the user has completed the form journey. If the user later chooses to modify an answer, especially one that affects the journey, the runner will return to the Summary page. Here, it will assess whether any mandatory answers are missing, and if so, prompt the user to complete these answers before moving on to the next required page and it will continue this till reaching the end.
And to fix this I have introduced a default section
=> FS-4777: adding fab default section while creating the pages, and this will automatically add into each page if a section is not available

designer/client/components/Page/AdapterPage.tsx
https://mhclgdigital.atlassian.net/browse/FS-4779
When a user tries to create a new form as a template, the form initially displays a three-page view: First Page -> Second Page -> Summary. However, if the user adds a new page and wants to set it as the first page, the form's JSON does not update the startPage to reflect this change.
=> FS-4779-fix first page not selecting issue

designer/client/components/component-edit/AdapterComponentTypeEdit.tsx, designer/client/components/component-edit/NumberFieldEdit.tsx
https://mhclgdigital.atlassian.net/browse/FS-4782
When user decided to change the values it will change once changed focused so I have overridden the component to use onChange event instead so this will trigger once user changing the data
=> FS-4782: Fixing Number field not allowing to change additional configurations once doing the update 

runner/src/server/plugins/engine/api/RegisterFormPublishApi.ts
When a user wants to change the data from the summary page, and then he comes back and tries to save it gives a 404 since it cannot detect the last page because of the / we have, so with this change we are going to ignore the / that we have
=> In summary page data change gives a 404 while trying to complete after the data change

copilot/fsd-form-runner-adapter/manifest.yml
Add `fsd-pre-award-stores` to callback safelist in copilot manifest in order to successfully migrate application-store into the combined pre-award-stores.
=> BAU: Add pre-award-stores to callback safelist

copilot/fsd-form-designer-adapter/manifest.yml, copilot/fsd-form-runner-adapter/manifest.yml
This is because the `recreate` deployment method leads to downtime, which can disrupt our users (internally). It is not any faster than a normal deployment, and causes tests to break. I am not sure why it was chosen to begin with.
https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#deployment-rolling
=> Don't deploy with recreate

runner/src/server/plugins/engine/page-controllers/ConfirmPageController.ts
https://mhclgdigital.atlassian.net/browse/FLS-823
Description:
This update addresses the new HSRA requirements, which involve two different application task lists. We create a round for each task list and use eligibility questions to determine which round to redirect the user to based on their answer.
- We check the eligibility questions for the answer to a specific question.
- If the question exists, we retrieve its value (the round short code).
- We then pass this value to the frontend as a redirect_to_eligible_round parameter.
- This parameter is used to decide which application task list to display.
- Log in to the apply service to a fund that includes eligibility questions before starting an application.
- Ensure you are redirected to the correct task list based on the answer to the …
=> FLS-823: feature/redirect-to-eligible-round

runner/src/server/plugins/engine/models/ViewModelBase.ts, runner/src/server/views/repeating-summary.html, runner/src/server/views/summary.html
https://mhclgdigital.atlassian.net/browse/FS-4864
If there is a section for the forms and if it says to hide the section it should hide the section details 
Previously 
After the fix
=> FS-4864: If there is a section for the forms and if it says to hide the section it should hide the section details

.github/workflows/copilot_deploy.yml, copilot/fsd-form-runner-adapter/manifest.yml
https://mhclgdigital.atlassian.net/browse/FSPT-204
Adds the new `fsd-pre-award` deployed service to the form runner whitelist.
Also, we need to give these permissions to the workflow after merging [this update to the deployment pipeline](https://github.com/communitiesuk/funding-service-design-workflows/pull/223).
=> Integrate frontend and fix deployment

copilot/fsd-form-runner-adapter/manifest.yml
https://mhclgdigital.atlassian.net/browse/FSPT-207
We're switching from serving the pre-award internal/private API on `fsd-pre-award` to `fsd-pre-award.env.pre-award.local`, the latter of which is available to ECS scheduled tasks as well as full services.
We need the API to be available for scheduled tasks because the post-award download-report job runs this way and needs to read from the account-store API.
=> Add new safe callback host

copilot/fsd-form-runner-adapter/manifest.yml, runner/config/custom-environment-variables.json, runner/config/default.js, runner/package.json, runner/src/index.ts, runner/src/instrument.ts, runner/src/server/index.ts
**Ticket: https://mhclgdigital.atlassian.net/browse/FS-4940**
Implementing Sentry to monitor errors
=> FS-4940 sentry implementation for runner

.github/workflows/copilot_deploy.yml
Deploys to test, UAT and Prod will now trigger a Slack notification if the deployment fails as this would constitute a 'block' in the pipeline.
Relies on https://github.com/communitiesuk/funding-service-design-workflows/pull/231
Ticket: https://mhclgdigital.atlassian.net/browse/FSPT-220
=> FSPT-220: Enable Slack notification on failed deploys

runner/package.json
Adjust prod script.
From what I can see, `nodemon` even with the `NODE_ENV=production` it's still watching. 
If I do `make pre up` you would still see:
```
form-runner-1    | [nodemon] 2.0.22
form-runner-1    | [nodemon] to restart at any time, enter `rs`
form-runner-1    | [nodemon] watching path(s): dist/**/*
form-runner-1    | [nodemon] watching extensions: js,mjs,json
form-runner-1    | [nodemon] starting `node dist/digital-form-builder-adapter/runner/index.js`
```
=> Adjust prod script

fsd_config/form_jsons/lpdf_r2/lpdf-r2-local-authority-details.json
Add LPA's to the list of LA's.
LPDF and GBRF use a form component for Local Authority names.
LPDF R2 applicant mentioned he cannot find **Yorkshire Dales National Park Authority** on the list. We discovered we are currently not displaying LPA's at all.
This PR adds the LPA's but only for LPDF R2's form.
=> Add LPA's to the list of LA's

runner/src/server/plugins/engine/components/EmailAddressField.ts, runner/src/server/plugins/engine/components/index.ts, runner/src/server/plugins/engine/views/partials/form.html, runner/test/cases/server/plugins/engine/components/EmailAddressField.test.ts
https://mhclgdigital.atlassian.net/browse/FS-5018
Remove HTML5 validation and add email address validation in backend
- [ x] Unit tests and other appropriate tests added or updated
- [x ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
=> FS-5018: remove html5 validation and add email validation

copilot/fsd-form-designer-adapter/manifest.yml, copilot/fsd-form-runner-adapter/manifest.yml
Adds overrides on test environment to migrate to test.communities.gov.uk domain
After deployment test environment should be accessible on test.communities.gov.uk domain
=> FSPT-228: add overrides on test environment

copilot/fsd-form-runner-adapter/manifest.yml
Adds UAT and PROD aliases, ahead of communities migration.
Also tests removing the hosted zone (as we don't use it on post-award i.e. https://github.com/communitiesuk/funding-service-design-post-award-data-store/blob/504e6dbd3bc6943c602cc134ac3b432f426bca8e/copilot/post-award/manifest.yml#L81 and that seems to deploy without issue.) 
Should add UAT and PROD aliases, but the communities domains should 404 until other config changes are made.
=> FSPT-228: Consolidate aliases and test removing hosted zone

copilot/fsd-form-designer-adapter/manifest.yml
We were erroneously duplicating this value. We only want to override in dev and test for now.
Should deploy successfully
=> FSPT-228: fix duplicate manifest declaration

copilot/fsd-form-runner-adapter/manifest.yml
Remove hosted zone that was causing deployment failure. (see https://github.com/communitiesuk/digital-form-builder-adapter/actions/runs/13725475079/job/38478280552) I have tested with other services that this is not required and the service should deploy without it being set.
Should deploy successfully after merge
=> FSPT-228: Remove hosted zone 

runner/src/server/plugins/engine/views/components/freetextfield.html
We see this warning in the browser console for tinymce because we haven't confirmed our license type:
TinyMCE is running in evaluation mode. Provide a valid license key or add license_key: 'gpl' to the init config to agree to the open source license terms.
=> Confirm GPL license for tinymce

copilot/fsd-form-runner-adapter/manifest.yml
Form runner is an extremely noisy application in terms of spans, and it's using the bulk of our tracing allowance in Sentry, which is exhausting our monitoring for other apps.
Until we can 1) refine the logs+metrics from form runner, and 2) increase our sentry quotas, this should bring the volume of form-runner spans down.
I don't think anyone is really using the span insights from dev/test/uat, so we can probably instead focus on generating spans from prod which might help debug live issues. Volume in prod is also far lower because we do not run any automated e2e tests, and our user base is low volume.
form-runner across all envs has emitted about ~5m spans in the last 30 days, compared to ~1.5m from everything else combined.
=> Flip trace sampling rate

copilot/fsd-form-designer-adapter/manifest.yml, copilot/fsd-form-runner-adapter/manifest.yml
migrate UAT designer and runner to communities domain name
As all pre-production environments now share the config we can remove some duplication by moving them into the same config.
UAT should resolve at `.uat.communities.gov.uk` domain names post-deployment
=> FSPT-228: migrate UAT to communities domain name

designer/server/views/head.html
[Form Designer text in header not hyperlinked](https://mhclgdigital.atlassian.net/browse/FS-5054)
Converts the "Form Designer" text in the app header from a non-functional span to an actual link directing to the `/app` path. Users can now easily return to the main application dashboard by clicking on the header title. This behaviour is consistent with the FAB header.
=> FS-5054 - Hyperlink the Form Designer text in the app header

designer/client/components/AdapterComponent.tsx
[Use appropriate symbol for client-side file upload component in Designer](https://mhclgdigital.atlassian.net/browse/FS-5058)
This changes how the client-side file upload component is rendered in the Form Designer UI, distinguishing it from other components like text fields. We reuse the same symbol used by the FileUpload component in the base repo.
=> FS-5058 - Client-side file upload component symbol change

designer/client/components/component-create/AdapterComponentCreateList.tsx
[Remove "File upload" (server-side) component from Designer](https://mhclgdigital.atlassian.net/browse/FS-5060)
This component does not work, apparently. And we don't need it to either, as we use client-side file upload these days. This commit prevents it being listed as one of the available component types when you create a new component in the Designer.
=> FS-5060 - Makes the 'File upload' component unavailable in Designer

designer/client/components/component-edit/ClientSideFileUploadFieldEdit.tsx
Fixing issue whereby parameters including minimumRequiredFiles and showNoScriptWarning are not added at the expected nesting level of the component and so are not serialised as expected by the Runner.
Noticed during rollout of Communities for Afghans (CFA) Round 1, which includes client-side file upload fields.
=> Fix parameter nesting issues with client-side file upload field

runner/src/server/plugins/engine/components/MultilineTextField.ts, runner/src/server/plugins/engine/components/index.ts, runner/test/cases/server/plugins/engine/components/MultilineTextField.test.ts
**Ticket:https://mhclgdigital.atlassian.net/browse/FS-5055**
When I am checking the schema validation that they are using to validate maxWord count is totally wrong So I had to replace the logic into correct one 
Following is the way they have checked the max word count but  we should have `maxWords > wordCount;`
```
function inputIsOverWordCount(input, maxWords) {
/**
* This validation is copied from the govuk-frontend library to match their client side behaviour
* the {@link https://github.com/alphagov/govuk-frontend/blob/e1612b13771fb7ca9a58ee85393aec94a1849335/src/govuk/components/character-count/character-count.js#L91 | govuk-frontend} library
*/
const wordCount = input.match(/\S+/g).length || 0;
return maxWords > wordCount;
}
```
Create a Multiline input field via designer put max …
=> Replacing the incorrect xgovforms schema for this field with the new schema  

designer/client/components/Page/AdapterPage.tsx
**Ticket: https://mhclgdigital.atlassian.net/browse/FS-5059**
When the user creating the forms with client side file upload it needs to actually upload a file if it is a mandatory field to go beyond that page so here we have added a session identification to upload the file into S3 and it uses a prefix of `preview/uuid` 
In designer create a form add a client side file upload you should see that it is uploading in the preview mode since it has the `form_session_identifier`
=> Adding form session identifier to mimic the file upload behaviour in the dev test and uat

.github/workflows/copilot_deploy.yml, .github/workflows/deploy.yml
As per Jira ticket [FS-4946](https://mhclgdigital.atlassian.net/browse/FS-4946) we had run into issues with this repo where an older pipeline had been run against the UAT environment after more recent changes had been deployed, essentially reverting those changes as they did not feature in the older built image.
In the pre-award and data-store workflows we have avoided this issue by setting concurrency groups on the deploy jobs, and also then using a matrix strategy in the called workflow to run deployments in parallel. Any 'pending' jobs that haven't been approved are automatically cancelled by newer jobs with the same concurrency group (see [GitHub actions docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and- …
=> FS-4946: Prevent outdated deployments

runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts, runner/src/server/plugins/engine/page-controllers/SummaryPageController.ts, runner/src/server/views/layout.html, runner/src/server/views/partials/preview-banner.html, runner/src/server/views/summary.html
[Don't show "Go back to application overview" in Form Runner previews](https://mhclgdigital.atlassian.net/browse/FS-5023) , 
[Add a banner for preview mode to notify users that no data is saved during testing (Manage Application Configuration)](https://mhclgdigital.atlassian.net/browse/FS-4852)
When user opens the form through FAB or designer it should show the user that we are not saving any data so here in the parameter we send https://form-runner.levellingup.gov.localhost:3009/about-your-organisation/before-you-start?form_session_identifier=preview/ed595f07-b37d-4485-b264-819d400d9937 here we have preview so this is preview mode that we are going to use and based on that we show the banner in the runner 
Open a form from FAB or form designer also verified the changes with the apply …
=> Show preview mode on the forms if coming from designer or fab

fsd_config/form_jsons/cfa_r1/cfa-r1-your-project.json
Allow the Delivery plan to be pdf too.
Now it only allows spreadsheets.
=> Allow pdfs file uploads

copilot/fsd-form-runner-adapter/manifest.yml, runner/src/instrument.ts
Exclude /health-check from Sentry traces sampler as the internal health check requests are using up our transaction quota.
* set `SENTRY_DSN` and `SENTRY_TRACES_SAMPLE_RATE` in your env
* Add logging in block
* go to `/health-check` route, logging should indicate conditional block being reached
Post-deployment we can check that `/health-check` transactions are no longer being recorded in Sentry
=> FLS-1237: exclude health-check from Sentry traces sampler

runner/src/server/plugins/engine/views/components/freetextfield.html
Ticket: https://mhclgdigital.atlassian.net/browse/FLS-1138
- Refactor FreeTextField component to add ARIA attributes for resize handle to fix accessibility issue
- Run axe scan on a page that has tinymce freetextfield to ensure there is no issue
=> FLS-1138: Fix for accessibility bug in tinymce freetextfield

copilot/fsd-form-runner-adapter/manifest.yml, runner/src/server/plugins/engine/api/RegisterFormPublishApi.ts, runner/src/server/plugins/engine/api/RegisterS3FileUploadApi.ts
**Background**
File upload is broken in pre-prod environments. The client-side request to `/s3/.../create-pre-signed-url` gives a 302 response, leading to a CORS error and upload failure, see screenshot:
This has been an issue since this PR was merged five days ago: [FSPT-342 - Replace JWT auth with basic auth in pre-prod environments](https://github.com/communitiesuk/digital-form-builder-adapter/pull/178)
The issue is limited to Dev and Test environments as the change has not been deployed out to UAT, and the problem is limited to pre-prod anyway.
**What caused it?**
The main page routes (see `RegisterFormPublishApi.ts`) have JWT disabled in pre-prod. This means users / E2E tests do not obtain the application-level JWT cookie (`fsd_user_token`) after passing only perimeter basic auth. …
=> Fix - resolve file upload failures in pre-prod environments

.run/RUNNER.run.xml, e2e-test/README.md
https://mhclgdigital.atlassian.net/browse/FSPT-350
I've not touched the manifest here so that we are still associating the deployed app with both levellingup and communities domains. This is ostensibly for backwards compatibility and anyone who's eg bookmarked pages; however given this is for form designer and application questions, we could probably be much more aggressive with sunsetting the domains on this app specifically than with eg the pre- or post-award apps.
=> levellingup->communities domain changes

runner/src/server/plugins/engine/page-controllers/RepeatingFieldPageController.ts
The call to `getNext` was being passed the current page's post data, rather than the form session state, meaning that conditions weren't able to read the correct data to evaluate as true.
I've tested this locally but don't feel confident writing a good test in any meaningful amount of time. We'll have to test this thoroughly ourselves instead.
=> Fix next page for multi input pages

designer/client/components/multiinput-field-edit/MultiInputFieldEdit.tsx, e2e-test/cypress/e2e/designer/multiInputFieldEdit.feature, e2e-test/cypress/support/step_definitions/runner/i_configure_multiinput_field_max_rows.js, fsd_config/form_jsons/pfn_rp/pfn-rp-payment-profile-and-spend-forecast.json, runner/locales/cy.json, runner/locales/en.json, runner/src/server/plugins/engine/page-controllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/views/partials/form.html
[Add Tests and Designer Support for MultiInput Row Restriction in Digital Form Builder Adapter](https://mhclgdigital.atlassian.net/browse/FLS-1423)
- Moving the new multi-input field option maxMultiInputFieldRows to the component not the page
- Allowing multi-input row limit to be set in Designer
- Backend validation in Runner for multi-input field row limit
- Use 'Save' not 'Save and add another' on button if not possible to add another
- Using translation module for cleaner switch to Welsh on save button text
- Run Designer + Runner locally
- Go to Designer (@ https://form-designer.communities.gov.localhost:3000/app if you are running containers from Docker Runner repo)
- Click "Create a new form"
- Click "Import saved form" and select …
=> FLS-1423 - Multi-input field row limit

runner/src/server/views/summary.html
**Ticket: https://mhclgdigital.atlassian.net/browse/FLS-1409**
This PR addresses Issue ID: DAC_Missing_Error_Summary_01, which highlights the absence of an error summary on the ‘Check your answers’ page when a user attempts to proceed with incomplete or incorrect information.
Page Affected: Summary page (last page)
Go to any of the summary page also grant should have the mark-as-complete enabled
=> FLS-1409: Add Error Summary to 'Check Your Answers' Page for Accessibility Compliance

e2e-test/cypress/e2e/runner/getConditionEvaluationContext.feature, e2e-test/cypress/support/step_definitions/common/i_go_back.js, e2e-test/cypress/support/step_definitions/runner/back_link_fallback.js, runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts, runner/src/server/plugins/engine/page-controllers/SummaryPageController.ts, runner/src/server/plugins/engine/util/navigationUtils.ts, runner/src/server/plugins/utils/UtilHelper.ts, runner/src/server/views/layout.html, runner/src/server/views/summary.html, runner/test/cases/server/plugins/engine/page-controllers/ConfirmPageController.test.ts, runner/test/cases/server/plugins/engine/page-controllers/SummaryPageController.test.ts
🔗 https://mhclgdigital.atlassian.net/browse/FLS-1413
---
This PR addresses accessibility audit recommendations by improving sequential navigation within the Apply service forms. Previously, all form pages displayed a backlink labeled **"Go back to application overview"** (Summary page didn't show backlink), which redirected users to the task list. This disrupted the expected step-by-step navigation experience.
- **First page of the form**: Backlink text remains **"Go back to application overview"**.
- **Subsequent pages (including summary)**: Backlink text is now **"Go back to previous page"**, enabling users to navigate backward through the form sequentially.
- Refactored navigation logic into a shared utility (`navigationUtils`) for consistent behavior across controllers.
- Updated …
=> FLS-1413: Update backlink text and logic

designer/client/components/component-edit/AdapterFieldEdit.tsx, runner/src/server/plugins/engine/components/ClientSideFileUploadField.ts
Content Designer Jenny flagged issues she noticed when previewing a form containing a client-side file upload component. Specifically:
> In Costs and value for money task, the question 'Upload your project budget with a breakdown of the key costs of your project' - this needs to be mandatory. I didn't select the checkbox 'Make Client side field upload field optional' which I thought would make it mandatory, but it looks like I can still skip the question. I then changed the default 'Minimum required files count' from 0 to 1 (as that seems like it would make it mandatory). This seemed to have worked in the sense that an error message now shows if there are no files uploaded, but the files I tried to upload would disappear and the error message doesn't go away
There are two issues here - …
=> Bugfix - Client-side file upload field - remove make field optional checkbox + fix component validation in preview mode
