communitiesuk/digital-form-builder-adapter

designer/client/AdapterComponent.tsx, designer/client/AdapterComponentEdit.tsx, designer/client/AdapterComponentTypeEdit.tsx, designer/client/AdapterDesigner.tsx, designer/client/FreeTextFieldEdit.tsx, designer/client/components/ComponentCreate/AdapterComponentCreate.tsx, designer/client/components/ComponentCreate/AdapterComponentCreateList.tsx, designer/client/components/Page/AdapterPage.tsx, designer/client/components/Page/index.ts, designer/client/components/Visualization/AdapterVisualisation.tsx, designer/client/components/Visualization/index.tsx, designer/client/i18n/i18n.tsx, designer/client/i18n/index.ts, designer/client/i18n/translations/cy.translation.json, designer/client/i18n/translations/en.translation.json, designer/client/index.tsx, designer/package.json, designer/webpack.config.js, model/src/components/component-types.ts, model/src/components/index.ts, model/src/components/types.ts
Adding the freetextfield into designer
=> FS-4567: Feature - Form Builder & Runner - Free text field component creation

.github/workflows/copilot_deploy.yml, .gitmodules, copilot/.workspace, copilot/fsd-form-runner/addons/form-runner-data.yml, copilot/fsd-form-runner/manifest.yml
=> FS-4570 deployment fixes

runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts, runner/src/server/plugins/engine/views/index.html, runner/src/server/plugins/engine/views/partials/form.html, runner/src/server/plugins/utils/UtilHelper.ts, runner/src/server/views/summary.html
https://dluhcdigital.atlassian.net/browse/FS-4581
adding backlink changes and save button text change
=> FS-4581: adding backlink and button text change

model/src/components/index.ts
=> adding a build fix

copilot/fsd-form-runner-adapter/addons/form-runner-data.yml, copilot/fsd-form-runner-adapter/manifest.yml
Fix the deployment issues for the form runner adapter service implementation in the AWS environment.
Please delete options that are not relevant.
Service has been successfully deployed locally in Dev AWS environment.
=> FS-4577: Fix AWS Deployment 

fsd_config/form_jsons/hsra_r1/other-costs-hsra.json, fsd_config/form_jsons/hsra_r1/refurbishment-costs-hsra.json, fsd_config/form_jsons/hsra_r1/vacant-property-details-hsra.json, fsd_config/form_jsons/night_shelter/building-works-ns.json, runner/Dockerfile, runner/src/client/sass/application.scss, runner/src/server/plugins/ViewLoaderPlugin.ts, runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts, runner/src/server/plugins/engine/page-controllers/ValidationOptions.ts
=> FS-4573 bug fixes

designer/client/AdapterDesigner.tsx, designer/client/AdapterPageCreate.tsx, designer/client/components/Visualization/AdapterLines.tsx, designer/client/components/Visualization/AdapterVisualisation.tsx, designer/client/components/component-create/links/AdapterLinkCreate.tsx, designer/client/components/component-edit/link-edit/AdapterLinkEdit.tsx, designer/client/components/menu/AdapterMenu.tsx, designer/client/conditions/AdapterSelectConditions.tsx, docker-compose.yml, runner/src/server/plugins/engine/page-controllers/SummaryPageController.ts
conditions bug fix and docker compose fix
=> conditions bug fix and docker compose fix

designer/client/components/component-edit/ClientSideFileUploadFieldEdit.tsx, runner/src/server/plugins/engine/Auth.ts, runner/src/server/plugins/engine/api/RegisterFormPublishApi.ts, runner/src/server/plugins/engine/api/RegisterS3FileUploadApi.ts
adding auth disable based on configuration and client side file upload fix
=> FS-4602: adding auth disable based on configuration and client side file upload fix

runner/package.json, runner/src/server/services/S3UploadService.ts, yarn.lock
https://dluhcdigital.atlassian.net/browse/FS-4598
updating aws sdk into v3 for s3 service
=> FS-4598: updating aws sdk into v3 for s3 service

.github/workflows/copilot_deploy.yml, copilot/fsd-form-designer-adapter/manifest.yml
=> Deployment fix

runner/src/server/plugins/engine/components/FreeTextField.ts, runner/src/server/plugins/engine/components/MultiInputField.ts, runner/src/server/plugins/engine/components/types.ts, runner/src/server/plugins/engine/page-controllers/DefaultPageController.ts, runner/src/server/plugins/engine/page-controllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/views/partials/form.html
[FS-2506](https://dluhcdigital.atlassian.net/browse/FS-2506)
fix the multi line text field component issue related to summary page & adapter related bug fix
=> FS-2506: fix the multi line text field component issue related to summary page & adapter related bug fix

runner/src/server/plugins/engine/components/UkAddressField.ts
https://dluhcdigital.atlassian.net/browse/FS-4021
- Instead of storing optional address fields if left empty as null, removing them from the output saved
- When putting the values back from the db to form, use county values to identify optional field
- Use any form with UKAddressField Component to fill only required fields and notice how the values are stored in the DB, they should not include null, just the required values separated by commas.
- Save the form in the application store after reaching the summary page and clicking save and continue.
- Log out and log back in and verify if you get the values in the their correct position in the address fields.
- Do this for all cases e.g. 3 req fields, 3 req fields + 1 optional addressField2, 3 req fields + 1 optional county field and …
=> FS-4021: Do not store optional address fields as null values in the DB

.github/workflows/copilot_deploy.yml, docker-compose.e2e.yml, runner/config/custom-environment-variables.json, runner/config/default.js, runner/src/server/index.ts, runner/src/server/services/MockUploadService.ts
Adding a fix for the e2e testing
=> Adding a fix for the e2e testing

.github/workflows/copilot_deploy.yml, copilot/fsd-form-designer-adapter/manifest.yml, docker-compose.e2e.yml, runner/src/server/index.ts
=> FS-4618 e2e testing

runner/src/server/plugins/engine/components/FreeTextField.ts, runner/src/server/plugins/engine/components/MultiInputField.ts, runner/src/server/plugins/engine/components/types.ts, runner/src/server/plugins/engine/models/AdapterFormModel.ts, runner/src/server/plugins/engine/models/AdapterViewModel.ts, runner/src/server/plugins/engine/models/Outputs.ts, runner/src/server/plugins/engine/models/ViewModelBase.ts, runner/src/server/plugins/engine/models/WebhookModel.ts
adding new data types & data conversion logic into adapter
=> adding new data types & data conversion logic into adapter

copilot/fsd-form-designer-adapter/manifest.yml
=> adding designer url fix

runner/src/server/plugins/engine/components/WebsiteField.ts
=> Adding a fix for the website field

copilot/fsd-form-runner-adapter/manifest.yml, runner/src/server/plugins/engine/components/UkAddressField.ts, runner/src/server/plugins/engine/models/AdapterFormModel.ts, runner/src/server/plugins/engine/models/AdapterSummaryViewModel.ts, runner/src/server/plugins/engine/models/AdapterViewModel.ts, runner/src/server/plugins/engine/models/ViewModelBase.ts, runner/src/server/plugins/engine/models/WebhookModel.ts, runner/src/server/plugins/engine/page-controllers/DefaultPageController.ts, runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts, runner/src/server/plugins/engine/page-controllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/page-controllers/RepeatingSummaryPageController.ts, runner/src/server/plugins/engine/page-controllers/SummaryPageController.ts, runner/src/server/services/AdapterCacheService.ts, runner/src/server/views/partials/summary-detail.html
https://dluhcdigital.atlassian.net/browse/FS-4668
https://dluhcdigital.atlassian.net/browse/FS-4704
With this PR I am going to fix following two issues 
01. Previously for every session it was used the same key since it is not attaching the forms session & with this PR I have resolved it 
2. Few issues happened with address field when coming into readonly summary page so with this PR that is also resolved
=> FS-4668/FS-4704: session management fixes and readonly summary fixes

.github/workflows/copilot_deploy.yml, docker-compose.e2e.yml
Adding caching & updating build steps to speed up the build
=> Build Improvements: Speedup the build process

copilot/fsd-form-runner-adapter/manifest.yml, runner/locales/cy.json, runner/locales/en.json, runner/package.json, runner/src/server/index.ts, runner/src/server/plugins/LanguagePlugin.ts, runner/src/server/plugins/ViewLoaderPlugin.ts, runner/src/server/plugins/engine/components/ClientSideFileUploadField.ts, runner/src/server/plugins/engine/page-controllers/DefaultPageController.ts, runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts, runner/src/server/plugins/engine/page-controllers/PlaybackUploadPageController.ts, runner/src/server/plugins/engine/page-controllers/ValidationOptions.ts, runner/src/server/plugins/engine/views/components/clientsidefileuploadfield.html, runner/src/server/plugins/engine/views/components/freetextfield.html, runner/src/server/types.ts, runner/src/server/views/layout.html, runner/src/server/views/summary.html, yarn.lock
https://dluhcdigital.atlassian.net/browse/FS-2947
https://dluhcdigital.atlassian.net/browse/FS-3953
Adding i18n language support for the runner
When in cof if select cy language then this will trigger process to select language
=> FS-2947/FS-3953 : adding language support with few language fixes for components

.github/workflows/copilot_deploy.yml
remove e2e check from deployment
=> remove e2e check from deployment

copilot/fsd-form-runner-adapter/manifest.yml
adding fix for the production alias
=> adding fix for the production alias

copilot/fsd-form-runner-adapter/manifest.yml, docker-compose.e2e.yml, runner/src/server/index.ts, runner/src/server/plugins/engine/MainPlugin.ts, runner/src/server/plugins/engine/api/RegisterApplicationStatusApi.ts, runner/src/server/plugins/engine/api/RegisterFormPublishApi.ts, runner/src/server/plugins/engine/api/RegisterS3FileUploadApi.ts, runner/src/server/plugins/engine/api/RegisterSessionApi.ts, runner/src/server/plugins/engine/application-status/RetryPay.ts, runner/src/server/plugins/engine/models/AdapterFormModel.ts, runner/src/server/plugins/engine/page-controllers/DefaultPageController.ts, runner/src/server/plugins/engine/page-controllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/page-controllers/RepeatingSummaryPageController.ts, runner/src/server/services/AdapterCacheService.ts, runner/src/server/services/AdapterStatusService.ts, runner/src/server/services/TranslationLoaderService.ts, runner/src/server/services/WebhookService.ts, runner/src/server/types.ts, runner/src/server/views/summary.html
https://mhclgdigital.atlassian.net/browse/FS-4728
https://mhclgdigital.atlassian.net/browse/FS-4666
Distributed cache for form definition and check webhook save is giving relevant status code
=> FS-4728: distributed cache for form definition and webhook changes

.github/workflows/anchore-scan.yml, .github/workflows/copilot_deploy.yml, designer/client/components/Page/AdapterPage.tsx, designer/client/components/component-create/AdapterComponentCreate.tsx, designer/client/components/component-edit/AdapterFieldEdit.tsx, designer/client/components/menu/AdapterMenu.tsx, designer/client/components/menu/SubMenu.tsx, designer/client/components/multiinput-field-edit/MultiInputFieldBaseEdit.tsx, designer/client/components/multiinput-field-edit/MultiInputFieldEdit.tsx, e2e-test/cypress/e2e/designer/multiInputFieldEdit.feature, e2e-test/cypress/support/step_definitions/runner/i_enter_child_components_to_multiinputfield_in_edit_field.js, e2e-test/cypress/support/step_definitions/runner/i_enter_table_title_names_to_multiinputfield_in_edit_field.js
https://mhclgdigital.atlassian.net/browse/FS-4742
With this issue fix this allow the user to add more multi input field configurations and fields from the designer side and added fixes to generate JSOn file with correct controllers init when multiinput field is being used.
=> Fix multi input field issue in designer side this has few issue fixes

fsd_config/form_jsons/cof25/en/applicant-information-cof.json, fsd_config/form_jsons/cof25/en/community-benefits-cof.json, fsd_config/form_jsons/cof25/en/community-engagement-cof.json, fsd_config/form_jsons/cof25/en/community-representation-cof.json, fsd_config/form_jsons/cof25/en/community-use-cof.json, fsd_config/form_jsons/cof25/en/declarations-cof.json, fsd_config/form_jsons/cof25/en/environmental-sustainability-cof.json, fsd_config/form_jsons/cof25/en/feasibility-cof.json, fsd_config/form_jsons/cof25/en/inclusiveness-and-integration-cof.json, fsd_config/form_jsons/cof25/en/local-support-25.json, fsd_config/form_jsons/cof25/en/operational-costs-cof.json, fsd_config/form_jsons/cof25/en/organisation-information-cof.json, fsd_config/form_jsons/cof25/en/project-information-cof-25.json, fsd_config/form_jsons/cof25/en/risk-cof.json, fsd_config/form_jsons/cof25/en/skills-and-resources-cof.json, fsd_config/form_jsons/cof25/en/upload-business-plan-cof-25.json, fsd_config/form_jsons/cof25/eoi/en/about-your-asset-25.json, fsd_config/form_jsons/cof25/eoi/en/declaration-25.json, fsd_config/form_jsons/cof25/eoi/en/development-support-provider-25.json, fsd_config/form_jsons/cof25/eoi/en/organisation-details-25.json, fsd_config/form_jsons/cof25/eoi/en/your-funding-request-25.json
Fixing the form names so the service title stays consistent
_A brief description of the pull request_
_If manual testing is needed, give suggested testing steps_
=> fixing form names

fsd_config/form_jsons/cof25/en/applicant-information-cof-25.json, fsd_config/form_jsons/cof25/en/asset-information-cof-25.json, fsd_config/form_jsons/cof25/en/community-benefits-cof-25.json, fsd_config/form_jsons/cof25/en/community-engagement-cof-25.json, fsd_config/form_jsons/cof25/en/community-representation-cof-25.json, fsd_config/form_jsons/cof25/en/community-use-cof-25.json, fsd_config/form_jsons/cof25/en/declarations-cof-25.json, fsd_config/form_jsons/cof25/en/environmental-sustainability-cof-25.json, fsd_config/form_jsons/cof25/en/feasibility-cof-25.json, fsd_config/form_jsons/cof25/en/funding-required-cof-25.json, fsd_config/form_jsons/cof25/en/inclusiveness-and-integration-cof-25.json, fsd_config/form_jsons/cof25/en/local-support-cof-25.json, fsd_config/form_jsons/cof25/en/operational-costs-cof-25.json, fsd_config/form_jsons/cof25/en/organisation-information-cof-25.json, fsd_config/form_jsons/cof25/en/project-information-cof-25.json, fsd_config/form_jsons/cof25/en/risk-cof-25.json, fsd_config/form_jsons/cof25/en/skills-and-resources-cof-25.json, fsd_config/form_jsons/cof25/en/upload-business-plan-cof-25.json, fsd_config/form_jsons/cof25/eoi/en/about-your-asset-25.json, fsd_config/form_jsons/cof25/eoi/en/declaration-25.json, fsd_config/form_jsons/cof25/eoi/en/development-support-provider-25.json, fsd_config/form_jsons/cof25/eoi/en/organisation-details-25.json, fsd_config/form_jsons/cof25/eoi/en/your-funding-request-25.json
Forms updated after latest fab export for COF25 and COF25-EOI
=> updated forms from fab

.github/workflows/copilot_deploy.yml
Adding the workflow fix when determining the environment
=> Adding the workflow fix when determining the environment

copilot/fsd-form-runner-adapter/manifest.yml, docker-compose.e2e.yml, docker-compose.yml, runner/src/server/plugins/engine/api/RegisterFormPublishApi.ts
ignore publish endpoint in production but allow in dev test uat environments
=> ignore publish endpoint in production but allow in dev test uat environments

designer/client/components/Page/AdapterPage.tsx
adding fix for the designer preview to pen the preview in a separate tab
=> adding fix for the designer preview

runner/src/server/plugins/engine/models/AdapterSummaryViewModel.ts, runner/src/server/plugins/engine/models/AdapterViewModel.ts, runner/src/server/plugins/engine/models/ViewModelBase.ts, runner/src/server/plugins/engine/page-controllers/DefaultPageController.ts, runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts, runner/src/server/plugins/engine/page-controllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/page-controllers/SummaryPageController.ts
https://mhclgdigital.atlassian.net/browse/FS-4781
Dynamically selecting the last page and then based on the answers it will select the last page that needs to go
=> FS-4781: Dynamic-Last page and allow the users to add more last pages

runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts
https://mhclgdigital.atlassian.net/browse/FS-4783
When the footer links are rendered they are missing the fund and round short names as a parameter because contact us and privacy policy URLs are fund and round specific URL's
=> FS-4783: Runner footer url fix for 404 issues

.run/DESIGNER No AUTH.run.xml, .run/README.md, .run/RUNNER  TEST.run.xml, .run/RUNNER No AUTH NO REDIS.run.xml, .run/RUNNER No AUTH.run.xml, .run/RUNNER-prod mode.run.xml, .run/RUNNER.run.xml, designer/client/components/Page/AdapterPage.tsx, designer/client/components/component-edit/AdapterComponentTypeEdit.tsx, designer/client/components/component-edit/NumberFieldEdit.tsx, designer/client/components/component-edit/TextFieldEdit.tsx, designer/client/components/multiinput-field-edit/MultiInputFieldEdit.tsx, e2e-test/cypress/e2e/designer/designerToRunnerFormBuild.feature, e2e-test/cypress/e2e/designer/multiInputFieldEdit.feature, e2e-test/cypress/support/step_definitions/runner/I_need_to_test_json_configuration_making_process_e2e.js, e2e-test/cypress/support/step_definitions/runner/i_enter_child_components_to_multiinputfield_in_edit_field.js, runner/compile-scss.js, runner/config/default.js, runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts, runner/src/server/plugins/engine/page-controllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/views/partials/form.html
https://mhclgdigital.atlassian.net/browse/FS-4772
https://mhclgdigital.atlassian.net/browse/FS-4821
- This PR introduces IntelliJ IDEA run configurations, making it easier for users to run the project locally. Additionally, it includes several enhancements related to the multi-input field component. These improvements address issues such as fixing the radio button not attaching the list to the multi-input field and implementing general updates needed to improve and standardise the multi-input field functionality.
- Also in this PR it will contains a e2e test which is going to cover a full path of creating a from to usage of it and it already covers the entire flow of designer and runner 
- This PR also contains a change to disable of logging headers in the response & request since those …
=> FS-4772/FS-4821: Adding Multi input field enhancements

.github/workflows/copilot_deploy.yml
https://github.com/communitiesuk/funding-service-pre-award-stores/pull/23
=> Pass AWS_ACCOUNT through to e2e test job

copilot/fsd-form-runner-adapter/manifest.yml, runner/config/default.js, runner/src/server/index.ts, runner/src/server/plugins/logging.ts
https://mhclgdigital.atlassian.net/browse/FS-4821
In this PR it will format the logging which is going to compatible with cloudwatch logs & this will omit all the sensitive data
=> FS-4821: loggin configuration changes to give more cloud watch friendly logs

fsd_config/form_jsons/dpif_r3/dpif-dataset-information.json, fsd_config/form_jsons/dpif_r3/dpif-declarations.json, fsd_config/form_jsons/dpif_r3/dpif-engaging-the-odp-community.json, fsd_config/form_jsons/dpif_r3/dpif-engaging-the-organisation.json, fsd_config/form_jsons/dpif_r3/dpif-future-work.json, fsd_config/form_jsons/dpif_r3/dpif-name-your-application.json, fsd_config/form_jsons/dpif_r3/dpif-organisation-information.json, fsd_config/form_jsons/dpif_r3/dpif-roles-and-recruitment.json, fsd_config/form_jsons/dpif_r3/dpif-your-skills-and-experience.json
1. Be on latest docker-runner and all other repos
2. Git checkout `run-dpif-r3` branch on:
- digital-form-builder-adapter
- funding-service-pre-award-stores
- funding-service-design-frontend
- funding-service-design-notification
3. `make up`
4. Annoying extra step because open date is in the future:
```
docker exec funding-service-pre-award-stores-1 python -m fund_store.scripts.amend_round_dates -q update-round-dates-fab --fund_short_name DPIF --round_short_name R3 -o PAST -d FUTURE
```
5. Go to https://frontend.levellingup.gov.localhost:3008/funding-round/DPIF/R3
=> Adding DPIF-R3 forms

fsd_config/form_jsons/gbrf_r1/gbrf-r1-eligibility.json, fsd_config/form_jsons/gbrf_r1/green-belt-declarations.json, fsd_config/form_jsons/gbrf_r1/green-belt-spending-proposals.json, fsd_config/form_jsons/gbrf_r1/local-plans-local-authority-details-signed-off.json, fsd_config/form_jsons/lpdf_r1/declarations-lpdf.json, fsd_config/form_jsons/lpdf_r1/local-plans-local-authority-details.json, fsd_config/form_jsons/lpdf_r1/lpdf-r1-eligibility.json, fsd_config/form_jsons/lpdf_r1/spending-proposals-lpdf.json
Adding LPDF R1 and GBRF R1 forms
=> Adding LPDF R1 and GBRF R1 forms

fsd_config/form_jsons/gbrf_r1/gbrf-r1-eligibility.json, fsd_config/form_jsons/gbrf_r1/green-belt-declarations.json, fsd_config/form_jsons/gbrf_r1/local-plans-local-authority-details-signed-off.json, fsd_config/form_jsons/lpdf_r1/local-plans-local-authority-details.json
Update forms:
- GBRF eligibility form updated
- GBRF declarations forn updated
- LPDF & GBRF authorities list updated
=> Update LPDF and GBRF forms

copilot/fsd-form-designer-adapter/manifest.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
_A brief description of the pull request_
_If manual testing is needed, give suggested testing steps_
=> basic auth quick fix

fsd_config/form_jsons/hsra_rp/applicant-information-hsra-rp.json, fsd_config/form_jsons/hsra_rp/hsra-rp-eligibility.json, fsd_config/form_jsons/hsra_rp/milestones-hsra-rp.json, fsd_config/form_jsons/hsra_rp/organisation-information-hsra-rp.json, fsd_config/form_jsons/hsra_vr/hsra-vr-eligibility.json
https://mhclgdigital.atlassian.net/browse/FLS-900
https://mhclgdigital.atlassian.net/browse/FLS-902
HSRA content changes for both rounds, requested by Fund Onboarding team.
=> HSRA content changes

fsd_config/form_jsons/hsra_vr/hsra-vr-eligibility.json
Adding space to get rid of empty string error
=> fixing error in hsra eligibility 

.github/workflows/submodule-tracking.yml
An automation which run on morning 3AM to check is there any new changes happen to the xgovforms submodule and if there are any changes only it will create a PR and inform us to merge the changes after manual check  (kind of dependant)
=> An automation which run on morning 3AM to check is there any new changes happen to the xgovforms submodule

fsd_config/form_jsons/gbrf_r1/local-plans-local-authority-details-signed-off.json, fsd_config/form_jsons/lpdf_r1/local-plans-local-authority-details.json
=> Fix LPDF and GBRP la name dropdown

fsd_config/form_jsons/hsra_vr/milestones-hsra-vr.json
https://mhclgdigital.atlassian.net/browse/FLS-916
- updated "post-payment verification (PPV)" to be "assurance form"
_If manual testing is needed, give suggested testing steps_
=> FLS-916: HSRA updates

fsd_config/form_jsons/hsra_rp/vacant-property-details-hsra-rp.json, fsd_config/form_jsons/hsra_vr/milestones-hsra-vr.json
https://mhclgdigital.atlassian.net/browse/FLS-838
https://mhclgdigital.atlassian.net/browse/FLS-916
- Replaced meters with metres
- post payment with post-payment
=> FLS-916: HSRA Content changes 16 Jan

runner/package.json
Add nodemon config to get autoreload enabled.
=> Add nodemon config

.github/workflows/copilot_deploy.yml, copilot/fsd-form-designer-adapter/manifest.yml
Previously only form runner was deployed on UAT. This adds form designer using the same matrix style as other environments
Should deploy successfully to UAT.
Have tested this by deploying the branch to UAT successfully
=> FS-4793: add form designer in UAT

copilot/fsd-form-runner-adapter/manifest.yml
Follow-up to correct config for communities domain overrides.
Flow should work correctly on communities domain.
=> FSPT-228: update env vars to be overriden to communities on dev and test

copilot/fsd-form-runner-adapter/manifest.yml
Switch over production environment variables to use communities domain name
Should resolve at communities domain name on production post-deployment
=> FSPT-228: switch to communities production for environment variables

fsd_config/form_jsons/uf1_r1/uf1-organisation-information.json, fsd_config/form_jsons/uf1_r1/uf1-project-details.json
Add UF1 forms.
Similar to the CTDF ones, but have a start page, which is integral to the Uncompeted journey.
Also has a file upload component.
=> Add uf1 forms

runner/locales/cy.json, runner/locales/en.json, runner/src/client/sass/application.scss, runner/src/server/plugins/engine/page-controllers/PageController.ts, runner/src/server/plugins/engine/page-controllers/StartPageController.ts, runner/src/server/views/layout.html, runner/src/server/views/partials/change-requests-banner.html, runner/test/cases/server/plugins/engine/page-controllers/PageController.test.ts, runner/test/cases/server/plugins/engine/page-controllers/StartPageController.test.ts
Add "no change needed" tag on pages that don't have change requests on re-submission.
=> Add no change needed tag

fsd_config/form_jsons/cham_reg/cham-reg-declarations.json, fsd_config/form_jsons/cham_reg/cham-reg-lead-contact-information.json, fsd_config/form_jsons/cham_reg/cham-reg-organisation-information.json, fsd_config/form_jsons/cham_reg/cham-reg-partner-organisations.json
Setup for Confronting Hate Against Muslims fund.
=> Configuring CHAM-REG fund

fsd_config/form_jsons/cham_apply/cham-apply-costs-and-value-for-money.json, fsd_config/form_jsons/cham_apply/cham-apply-organisation-information.json, fsd_config/form_jsons/cham_apply/cham-apply-programme-delivery.json, fsd_config/form_jsons/cham_apply/cham-apply-registration-details.json, fsd_config/form_jsons/cham_apply/cham-apply-risks-and-reporting-to-mhclg.json, fsd_config/form_jsons/cham_apply/cham-apply-upload-your-business-plan.json
Form files for CHAM Application round
=> CHAM fund, Application round

runner/config/default.js
Increase Session TTL.
More details on the investigation inside the Incident report.
=> Increase Session TTL

copilot/fsd-form-runner-adapter/overrides/README.md, copilot/fsd-form-runner-adapter/overrides/cfn.patches.yml
Increase log retention on form runner (this will give us increased visibility to analyse future incidents)
Log group retention period is 90 days after deployment
=> BAU: extend log retention period

copilot/fsd-form-runner-adapter/manifest.yml
PREVIEW_MODE is not disabled correctly on prod.
=> Make preview mode false on prod

runner/locales/cy.json, runner/locales/en.json, runner/src/server/views/summary.html
Ticket:
https://mhclgdigital.atlassian.net.mcas.ms/browse/FLS-1052
Description:
Change radio buttons on confirmation page to match new design. New text for _yes_ and _no_ options, and adds hint text to the _yes_ option.
Screenshot:
=> Change radio buttons on confirmation page to match new design

fsd_config/form_jsons/cham_apply/cham-apply-upload-your-business-plan.json
https://mhclgdigital.atlassian.net/browse/FLS-1293
=> Increase Cham business plan file size from 1Mb to 10MB

fsd_config/form_jsons/dpif_r4/dataset-information.json, fsd_config/form_jsons/dpif_r4/declarations.json, fsd_config/form_jsons/dpif_r4/engaging-the-odp-(open-digital-planning)-community.json, fsd_config/form_jsons/dpif_r4/engaging-the-organisation.json, fsd_config/form_jsons/dpif_r4/future-work.json, fsd_config/form_jsons/dpif_r4/name-your-application.json, fsd_config/form_jsons/dpif_r4/organisation-information.json, fsd_config/form_jsons/dpif_r4/roles-and-recruitment.json, fsd_config/form_jsons/dpif_r4/your-skills-and-experience.json
https://mhclgdigital.atlassian.net/browse/FLS-1324
Adding forms for DPIF R4 to do configuration
=> DPIF R4 forms

fsd_config/form_jsons/pfn_rp/pfn-rp-milestones.json
PFN-milestone form JSON next page fix
=> PFN-milestone form JSON next page fix

runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts
https://mhclgdigital.atlassian.net/browse/FLS-1130
File uploads in Form Runner preview mode had two critical issues:
- Summary page showed "Not supplied" instead of actual uploaded file names
- Files disappeared when navigating back to upload page from summary
The `form_session_identifier` was not being found because the code only looked in `state.metadata` but in FAB preview mode, it's stored in URL query parameters (`?form_session_identifier=preview/xyz`).
Without the session identifier, the S3 file lookup failed, causing empty file lists on summary page and no existing files shown on upload page.
Added fallback lookup for `form_session_identifier` in both `setExistingFilesToClientSideFileUpload()` for upload page file loading and `existingFilesToClientSideFileUpload()` for summary page …
=> Resolve file upload display issues in FAB preview mode

runner/src/server/plugins/engine/models/AdapterSummaryViewModel.ts, runner/src/server/plugins/engine/page-controllers/PageControllerBase.ts, runner/src/server/plugins/engine/util/windowTitle.ts, runner/src/server/views/layout.html
**Ticket:**
https://mhclgdigital.atlassian.net/browse/FLS-1415
**Description:**
This PR is one of two that update page titles to improve accessibility for screen reader users.
Link to related funding-service-pre-award PR:
https://github.com/communitiesuk/funding-service-pre-award/pull/531
Please find further details there.
=> Update page titles to assist screen reader users
